name: testing

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    
    runs-on: windows-latest

    steps:
      - name: testing
        run: |
          $version = get-date
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          
      - name: testing 2
        run: |
            echo ${{ env.BULID_VERSION }}
    
      
  
