name: Trigger Repo Dispatch

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  trigger-repo-dispatch:
   
    runs-on: ubuntu-latest

    steps:
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      
      - name: trigger event
        #env:
        #  MY_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: curl -H "Authorization: token ${{ steps.get_workflow_token.outputs.token }}" -H 'Accept: application/vnd.github.everest-preview+json' "https://api.github.com/repos/mickeygoussetorg/experimentation/dispatches"  -d '{"event_type": "deploy-code", "client_payload": {"please": "work"}}'
